nginx:
    build: ./nginx
    links:
        - myapp:myapp
    ports:
        - "80:80"
mongo:
    image: mongo
    ports:
        - "27017:27017"
    volumes:
        - mongodbdata:/data/db
myapp:
    build: .
    links:
        - mongo:mongo
    environment: 
        - NODE_ENV=production
    ports:
        - "3000"