db:
    image: mongo
    volumes:
        - mongodbdata:/data/db
redis:
    image: redis
    ports:
        - "6379"
    volumes:
        - redisdata:/data
myapp:
    build: .
    links:
        - db
    environment: 
        - MONGODB=mongodb://db/test
        - REDIS_HOST=redis://redis:6379
    ports:
        - "3000"
nginx:
    build: ./nginx
    links:
        - myapp
    ports:
        - "80:80"